#!/bin/bash

SRVUSER=gameserv
ADMINPREFS_FILE=/home/$SRVUSER/.loki/tribes2/Classic/scripts/autoexec/AdminPrefs.cs
SECRETS=/run/secrets

# -- set Admin Password
cat ${SECRETS}/t2.admin.password >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set classic SA PW
cat ${SECRETS}/t2.classic.superadmin.password >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set classic telnet listen password
cat ${SECRETS}/t2.classic.telnet.listen.password >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set classic telnet password
cat ${SECRETS}/t2.classic.telnet.password >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE


# -- set sa/admin lists
echo "\$Host::AdminList = \"${T2_ADMIN_LIST}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::SuperAdminList = \"${T2_SA_LIST}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set server name
echo "\$Host::GameName = \"${T2_SERVERNAME}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set mission type
echo "\$Host::MissionType = \"${T2_DEFAULT_MISSIONTYPE}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- time limit
echo "\$Host::TimeLimit = \"${T2_TimeLimit}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set map
echo "\$Host::Map = \"${T2_DEFAULT_MAP}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set max players
echo "\$Host::MaxPlayers = \"${T2_MAX_PLAYERS}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set telnet on/off
echo "\$Host::ClassicTelnet = ${T2_Telnet};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::ClassicTelnetPort = ${T2_Telnet_Port};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set admin voting options
echo "\$Host::allowAdminPlayerVotes = ${T2_VoteAdmin};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::EvoAdminMinPlayers = ${T2_VoteAdminPlayerMin};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::EvoAdminAdmin = ${T2_Admin2AdminOthers};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set baserape
echo "\$Host::EvoNoBaseRapeClassicPlayerCount = ${T2_BaseRapeMin};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::EvoNoBaseRapePlayerCount = ${T2_BaseRapeMin};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set turret min
echo "\$Host::EnableTurretPlayerCount = ${T2_TurretMin};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set cloak pack min
echo "\$Host::AntiCloakPlayerCount = ${T2_CloakMin};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set packet settings
echo "\$Host::ClassicPacketRateToClient = ${T2_PacketRate};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::ClassicPacketSize = ${T2_PacketSize};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set observer timeout
echo "\$Host::EvoKickObservers = ${T2_ObserverTimeout};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set ban time
echo "\$Host::BanTime = ${T2_BanTime};" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set empty server reset
if [ "T2_EmptyServerReset" = 1 ]
then
	echo "\$Host::EmptyServerReset = ${T2_EmptyServerReset};" >> $ADMINPREFS_FILE
    printf "\n" >> $ADMINPREFS_FILE
    echo "\$Host::EmptyServerResetTime = ${T2_EmptyServerResetTime};" >> $ADMINPREFS_FILE
    printf "\n" >> $ADMINPREFS_FILE
fi

# -- set PUG always on
if [ "$T2_PUGPW_ALWAYSON" = 1 ]
then
    echo "\$Host::PUGpasswordAlwaysOn = ${T2_PUGPW_ALWAYSON};" >> $ADMINPREFS_FILE
    printf "\n" >> $ADMINPREFS_FILE
fi

# -- set server/pug pw
echo "\$Host::PUGPassword =  \"${T2_PUG_PASSWORD}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::PUGautoPassword =  \"${T2_PUGAUTOPW_TOURNY}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set smurfs
echo "\$Host::NoSmurfs =  \"${T2_NoSmurfs}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set Evo Centerprint Banner
echo "\$Host::EvoMOTD = \"${T2_JoinBanner}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::EvoMOTDlines = \"${T2_JoinBannerLines}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::EvoMOTDtime = \"${T2_JoinBannerTime}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

# -- set Loading Screen Options
echo "\$Host::LoadScreenColor1 = \"${T2_LoadScreenColor1}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenColor2 = \"${T2_LoadScreenColor2}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenColor3 = \"${T2_LoadScreenColor3}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

echo "\$Host::LoadScreenLine1 = \"${T2_LoadScreenLine1}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine1_Msg = \"${T2_LoadScreenLine1_Msg}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine2 = \"${T2_LoadScreenLine2}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine2_Msg = \"${T2_LoadScreenLine2_Msg}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine3 = \"${T2_LoadScreenLine3}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine3_Msg = \"${T2_LoadScreenLine3_Msg}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine4 = \"${T2_LoadScreenLine4}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine4_Msg = \"${T2_LoadScreenLine4_Msg}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine5 = \"${T2_LoadScreenLine5}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine5_Msg = \"${T2_LoadScreenLine5_Msg}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine6 = \"${T2_LoadScreenLine6}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenLine6_Msg = \"${T2_LoadScreenLine6_Msg}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE

echo "\$Host::LoadScreenMOTD1 = \"${T2_LoadScreenMOTD1}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenMOTD2 = \"${T2_LoadScreenMOTD2}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenMOTD3 = \"${T2_LoadScreenMOTD3}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
echo "\$Host::LoadScreenMOTD4 = \"${T2_LoadScreenMOTD4}\";" >> $ADMINPREFS_FILE
printf "\n" >> $ADMINPREFS_FILE
