#!/bin/bash

echo "Removing old installers"
[ -f classic_v152.zip ] && rm classic_v152.zip
[ -f t2-linux.zip ] && rm t2-linux.zip
[ -f tribes2-lan-fix-linux.tar.gz ] && rm tribes2-lan-fix-linux.tar.gz
echo "Done!"


echo "Removing TacoServer TribesNext Incompatibilities"
# Remove zAdvancedStatsLogless.vl2: causes issues connecting without TN
[ -f $1Classic/zAdvancedStatsLogless.vl2 ] && rm $1Classic/zAdvancedStatsLogless.vl2
# Remove checkVer: Wont work anyway without TN
[ -f $1Classic/scripts/autoexec/zCheckVer.cs ] && rm $1Classic/scripts/autoexec/zCheckVer.cs
# We're using our own heartbeat to TN
[ -f $1Classic/scripts/autoexec/zAltAltHeartbeatDaemon.cs ] && rm $1Classic/scripts/autoexec/zAltAltHeartbeatDaemon.cs

echo "Done!"