#!/bin/bash

# -- Generate an alphabetized autoexec index file because we can't trust the load order
SCRIPTS_DIR=$1
INDEX_FILE="$SCRIPTS_DIR"/autoexec/AAutoExecIndex.cs

mkdir -p "$SCRIPTS_DIR"/autoexec/library
mv -v "$SCRIPTS_DIR"/autoexec/*.cs "$SCRIPTS_DIR"/autoexec/library/.

scripts=(
   "$SCRIPTS_DIR"/autoexec/library/*.cs
)

for i in "${scripts[@]##*/}"
do
    echo "library/${i}" >> $INDEX_FILE
done

cat $INDEX_FILE