#!/bin/bash

BASE_DIR=/home/gameserv/.loki/tribes2/

echo "Update Admin & Server Prefs..."
/tmp/tribes2/cfg-admin-prefs
echo "Finished!"

cd ${BASE_DIR}

echo "Generating alphabetized AutoExec script index..."
/tmp/tribes2/gen_autoexec_index "${BASE_DIR}Classic/scripts"
echo "Finished!"

echo "Removing .dso files"
find ${BASE_DIR} -name \*.dso -execdir /bin/rm {} \;

echo "Running the Tribes 2 server"
chmod +x ${BASE_DIR}tribes2d-lan.dynamic

# -- debug -- keep container running and dont launch the server
#tail -f /dev/null

/tmp/tribes2/tn_heartbeat & taskset -c 0 ./tribes2d-lan.dynamic 28000 -nologin -dedicated -mod Classic