#!/bin/bash

export WINEPREFIX=/home/gameserv/.wine 
BASEDIR=$WINEPREFIX/drive_c/Dynamix/Tribes2/GameData

echo "Update Admin & Server Prefs..."
/tmp/tribes2/cfg-admin-prefs
echo "Finished!"


find ${BASEDIR} -name \*.dso -execdir /bin/rm {} \;

cd $WINEPREFIX/drive_c/Dynamix/Tribes2/GameData 

echo "Running the Tribes 2 server"
xvfb-run -a -w 5 \
wine Tribes2.exe -dedicated -mod Classic
