#!/bin/bash

# -- Heartbeat to TribesNext's Master Server

( 
  while true; do
    echo "Sending heartbeat to TribesNext..."
    curl http://master.tribesnext.com/add/28000 & 
    sleep 240 ;
  done
)